name: amazon
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  cloudinary_public: ^0.21.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.1.0
  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
